### ISSUE TITLE
OTA timeouted

### ISSUE THREAD

**Issue by mrkale** [raphitheking/photon-wdgs#2]
After applying the watchdog it not possible to OTA flash the Photon. Flashing is always ending up with time out. Only the manual resetting to safe mode helps. This issue persists at using the firmware example as well as at using the watchdog in a custom application.

**Comment by ryandamico** [comment]
Same issue here. This is a deal breaker for using an otherwise awesome library.

**Comment by flaz83** [comment]
Same issue here. I've to remove it...

**Comment by flaz83** [comment]
It seems that the problem is if(System.updatesPending()), not called on the last firmware.
I fixed it in this way:
removed this piece of code from _tickleWDGs:

```
 // deactivate WWDG if OTA updates pending
    If(System.updatesPending()) {
       if(PhotonWdgs::_wwdgRunning) {
           WWDG_DeInit();
       }
       System.enableUpdates();
       PhotonWdgs::_wdgTimer.end();
    }
```

Added this line at the bottom of begin()

`System.on(firmware_update_pending, handle_update);`

Added this method:

```
 void handle_update(system_event_t event, int param)
    {
        Serial.println("UPDATE READY WDGS");
        if(PhotonWdgs::_wwdgRunning) {
            WWDG_DeInit();
        }
        System.enableUpdates();
        PhotonWdgs::_wdgTimer.end();
    }
```

It seems to work, let me know if this is working also for you.
Flavio

**Comment by mrkale** [comment]
Yes, it works. Thank you for your fix. I had to fork the repository and import it to Particle Cloud as my private library in order to test it.

Now you can make a pull request or publish your version in Particle Cloud under your maintanence, if the original author does not accept it.

I recommend to ammend the new method's declaration to "**PhotonWdgs::**handle_update", remove "Serial ..." from it as well as put it in the header file to the interface.

**Comment by nielsclausen** [comment]
@flaz83: it works for me as well.

What is the status? I've made the changes to a local fork as well. Even though I'm not sure what the two sets of double asterix are doing @mrkale ?
> "**PhotonWdgs::**handle_update"

I just used regular declaration: 
> PhotonWdgs::handle_update

I'v uploaded my own private version of the library (do not want to confuse...). Should I issue a pull request with "my" updates?

**Comment by Phsacar** [comment]
Revived the project - Working on fixing it! 
Thanks @flaz83  for finding a solution!

**Comment by Phsacar** [comment]
This fix isn't working reliable on Particle Device OS  >1.2 as update pending is a "enterprise" feature.
Changed the library so that it detects if you enable "Force OTA" and disables the watchdog.
So if you want to update your code simply enable Force OTA on your device -> update -> disable force OTA as of current photon-wdgs version.
